### ISSUE TITLE
Problème alloc mem ajoute point et retire point

### ISSUE THREAD

**Issue by Tyrannide** [Mic-Firapat/K-PPV-UJM-PROJET#15]
Dans la dernière version (celle de la branche), il y a l'implémentation des interactions suivantes 👍🏻 
  - Ajoute un point quand tu cliques
  - Supprime un point quand tu cliques
  - Donnes une classe avec input_box
Cependant : 
- Donnes une classe ne marche pas, sans que j'en ai la raison  concrète
- Ajoute un point crash si tu cliques plus de deux fois (que tu peux empecher en reinitialisant la fenetre).
- Suppression point marche seulement si tu ne le cumules pas avec l'une des deux autres interactions ci-dessus.

**Comment by Mic-Firapat** [comment]
Ta version du Module Point était obsolète, tu t'es sans doute mélangé avec le github en postant tout tes fichiers avant de récupérer les miens. J'ai remis ce qu'il fallait, corriger tes mallocs et tes accès au tableau. Le changement de classe a été corrigé aussi et attention il faut pas utiliser CMAX mais nbclasses pour tenir compte du vrai nombre de classes actuel du fichier.
